language: java
sudo: false
git:
  depth: 1
  submodules: true
cache:
  directories:
    - $HOME/.m2
notifications:
  irc:
    channels:
      - irc.freenode.net#georchestra
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
install: ./mvnw --no-transfer-progress -B install -DskipTests -P-all,travis -Dadditionalparam=-Xdoclint:none
script: ./mvnw --no-transfer-progress verify -P-all,travis -Dadditionalparam=-Xdoclint:none
addons:
  apt:
    packages:
      - ant
      - ant-optional
      - python-virtualenv
      - python-pip
