version: '2'
services:
  ldap:
    image: georchestra/ldap
    build: ./
    environment:
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_ORGANIZATION=geOrchestra
      - SLAPD_ADDITIONAL_MODULES=groupofmembers
      - SLAPD_PASSWORD=secret
      - SLAPD_LOG_LEVEL=32768
    ports:
      - '3899:389'
