name: "datafeeder"
on:
  push:
    paths:
      - "datafeeder/**"
  pull_request:
    paths:
      - "datafeeder/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: "Checking out"
      uses: actions/checkout@v1

    - name: "Setting up Java"
      uses: actions/setup-java@v1
      with:
        java-version: '8.x'

    - name: "Configuring Maven"
      run: |
          mkdir -p $HOME/.m2
          # revisit? can't resolve org.openapitools:openapi-generator-maven-plugin:jar:5.0.1 in artifactory-georchestra
          #cp .github/resources/m2-settings.xml $HOME/.m2/settings.xml

    - name: "Maven repository caching"
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: "Installing & checking formatting"
      run: ./mvnw -f datafeeder/ --no-transfer-progress -B -Dfmt.action=validate install -Dadditionalparam=-Xdoclint:none -DskipTests

    - name: "Running Unit Tests"
      run: ./mvnw -f datafeeder/ test -DskipITs=true -DskipTests=false -ntp -Dfmt.skip=true -Dadditionalparam=-Xdoclint:none

    - name: "Running Integration Tests"
      run: ./mvnw -f datafeeder/ verify -DskipITs=false -DskipTests=true -ntp -Dfmt.skip=true -Dadditionalparam=-Xdoclint:none

    - name: Getting image tag
      if: github.repository == 'georchestra/georchestra'
      id: version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: "Building docker image"
      if: github.repository == 'georchestra/georchestra'
      run: ./mvnw clean package docker:build -Pdocker -DskipTests --pl datafeeder -DdockerImageName=georchestra/datafeeder:${{ steps.version.outputs.VERSION }}

    - name: "Logging in docker.io"
      if: github.repository == 'georchestra/georchestra'
      uses: azure/docker-login@v1
      with:
        username: '${{ secrets.DOCKER_HUB_USERNAME }}'
        password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

    - name: "Pushing latest to docker.io"
      if: github.ref == 'refs/heads/master' && github.repository == 'georchestra/georchestra'
      run: |
        docker tag georchestra/datafeeder:${{ steps.version.outputs.VERSION }} georchestra/datafeeder:latest
        docker push georchestra/datafeeder:latest

    - name: "Pushing release branch to docker.io"
      if: contains(github.ref, 'refs/heads/21.') && github.repository == 'georchestra/georchestra'
      run: |
        docker push georchestra/datafeeder:${{ steps.version.outputs.VERSION }}

    - name: "Pushing release tag to docker.io"
      if: contains(github.ref, 'refs/tags/21.') && github.repository == 'georchestra/georchestra'
      run: |
        docker push georchestra/datafeeder:${{ steps.version.outputs.VERSION }}

    - name: "Remove SNAPSHOT jars from repository"
      run: |
        find .m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
